name: Deploy Guard Workflow

on:
  workflow_call:
    outputs:
      allow:
        description: "Whether deploy is allowed."
        value: ${{ steps.check.outputs.allow }}

jobs:
  check_guard:
    runs-on: ubuntu-latest
    outputs:
      allow: ${{ steps.check.outputs.allow }}
    steps:
      - id: check
        run: |
          value="${{ vars.ALLOW_DEPLOY }}"
          value_lower=$(echo "$value" | tr '[:upper:]' '[:lower:]')

          if [ "$value_lower" = "true" ]; then
            echo "allow=true" >> $GITHUB_OUTPUT
          else
            echo "allow=false" >> $GITHUB_OUTPUT
          fi