name: Deploy Guard Workflow
on:
  workflow_call:
    outputs:
      allow:
        description: "Whether deploy is allowed."
        value: ${{ jobs.check_guard.outputs.allow }}

jobs:
  check_guard:
    runs-on: ubuntu-latest
    outputs:
      allow: ${{ steps.guard.outputs.allow }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check ALLOW_DEPLOY variable
        id: guard
        shell: bash
        run: |
          value="${{ vars.ALLOW_DEPLOY }}"
          value_lower=$(echo "$value" | tr '[:upper:]' '[:lower:]')

          if [ "$value_lower" = "true" ]; then
            echo "allow=true" >> $GITHUB_OUTPUT
            echo "✅ Deploy allowed"
          else
            echo "allow=false" >> $GITHUB_OUTPUT
            echo "🚨 Deploys disabled by org variable"
